set (SOURCES
./external/fatfs/doc/res/app2.c
./external/fatfs/doc/res/app4.c
./external/fatfs/doc/res/app3.c
./external/fatfs/doc/res/app1.c
./external/fatfs/src/ff.c
./external/fatfs/src/option/cc950.c
./external/fatfs/src/option/cc936.c
./external/fatfs/src/option/cc949.c
./external/fatfs/src/option/unicode.c
./external/fatfs/src/option/cc932.c
./external/fatfs/src/option/ccsbcs.c
./external/fatfs/src/option/syscall.c
./external/fatfs/src/diskio.c
./external/fatfs/port/diskio_blkdev.c
./external/utf_converter/utf.c
./external/mbedtls/library/ecdsa.c
./external/mbedtls/library/poly1305.c
./external/mbedtls/library/x509_csr.c
./external/mbedtls/library/ecp.c
./external/mbedtls/library/md5.c
./external/mbedtls/library/des.c
./external/mbedtls/library/md4.c
./external/mbedtls/library/pkcs12.c
./external/mbedtls/library/x509write_crt.c
./external/mbedtls/library/pkcs5.c
./external/mbedtls/library/ssl_ciphersuites.c
./external/mbedtls/library/aria.c
./external/mbedtls/library/timing.c
./external/mbedtls/library/certs.c
./external/mbedtls/library/version.c
./external/mbedtls/library/ecp_curves.c
./external/mbedtls/library/cipher_wrap.c
./external/mbedtls/library/base64.c
./external/mbedtls/library/nist_kw.c
./external/mbedtls/library/ecjpake.c
./external/mbedtls/library/pk_wrap.c
./external/mbedtls/library/blowfish.c
./external/mbedtls/library/debug.c
./external/mbedtls/library/cipher.c
./external/mbedtls/library/chacha20.c
./external/mbedtls/library/gcm.c
./external/mbedtls/library/ecdh.c
./external/mbedtls/library/x509write_csr.c
./external/mbedtls/library/error.c
./external/mbedtls/library/entropy.c
./external/mbedtls/library/cmac.c
./external/mbedtls/library/rsa.c
./external/mbedtls/library/entropy_poll.c
./external/mbedtls/library/ssl_cookie.c
./external/mbedtls/library/oid.c
./external/mbedtls/library/pk.c
./external/mbedtls/library/hkdf.c
./external/mbedtls/library/threading.c
./external/mbedtls/library/ctr_drbg.c
./external/mbedtls/library/padlock.c
./external/mbedtls/library/hmac_drbg.c
./external/mbedtls/library/ssl_ticket.c
./external/mbedtls/library/net_sockets.c
./external/mbedtls/library/xtea.c
./external/mbedtls/library/ssl_tls.c
./external/mbedtls/library/pkcs11.c
./external/mbedtls/library/aes.c
./external/mbedtls/library/camellia.c
./external/mbedtls/library/memory_buffer_alloc.c
./external/mbedtls/library/md.c
./external/mbedtls/library/aesni.c
./external/mbedtls/library/md2.c
./external/mbedtls/library/pem.c
./external/mbedtls/library/ssl_cache.c
./external/mbedtls/library/x509_crt.c
./external/mbedtls/library/ccm.c
./external/mbedtls/library/rsa_internal.c
./external/mbedtls/library/havege.c
./external/mbedtls/library/ssl_cli.c
./external/mbedtls/library/chachapoly.c
./external/mbedtls/library/dhm.c
./external/mbedtls/library/x509_create.c
./external/mbedtls/library/version_features.c
./external/mbedtls/library/asn1write.c
./external/mbedtls/library/sha1.c
./external/mbedtls/library/sha512.c
./external/mbedtls/library/pkparse.c
./external/mbedtls/library/platform_util.c
./external/mbedtls/library/x509.c
./external/mbedtls/library/pkwrite.c
./external/mbedtls/library/md_wrap.c
./external/mbedtls/library/x509_crl.c
./external/mbedtls/library/asn1parse.c
./external/mbedtls/library/ripemd160.c
./external/mbedtls/library/sha256.c
./external/mbedtls/library/platform.c
./external/mbedtls/library/ssl_srv.c
./external/mbedtls/library/arc4.c
./external/mbedtls/library/bignum.c
./external/mbedtls/programs/util/pem2der.c
./external/mbedtls/programs/util/strerror.c
./external/mbedtls/programs/hash/hello.c
./external/mbedtls/programs/hash/generic_sum.c
./external/mbedtls/programs/random/gen_random_havege.c
./external/mbedtls/programs/random/gen_entropy.c
./external/mbedtls/programs/random/gen_random_ctr_drbg.c
./external/mbedtls/programs/wince_main.c
./external/mbedtls/programs/x509/crl_app.c
./external/mbedtls/programs/x509/cert_write.c
./external/mbedtls/programs/x509/req_app.c
./external/mbedtls/programs/x509/cert_app.c
./external/mbedtls/programs/x509/cert_req.c
./external/mbedtls/programs/aes/crypt_and_hash.c
./external/mbedtls/programs/aes/aescrypt2.c
./external/mbedtls/programs/ssl/mini_client.c
./external/mbedtls/programs/ssl/ssl_server.c
./external/mbedtls/programs/ssl/ssl_fork_server.c
./external/mbedtls/programs/ssl/ssl_client2.c
./external/mbedtls/programs/ssl/dtls_server.c
./external/mbedtls/programs/ssl/ssl_mail_client.c
./external/mbedtls/programs/ssl/query_config.c
./external/mbedtls/programs/ssl/ssl_pthread_server.c
./external/mbedtls/programs/ssl/ssl_server2.c
./external/mbedtls/programs/ssl/dtls_client.c
./external/mbedtls/programs/ssl/ssl_client1.c
./external/mbedtls/programs/pkey/rsa_decrypt.c
./external/mbedtls/programs/pkey/ecdsa.c
./external/mbedtls/programs/pkey/pk_encrypt.c
./external/mbedtls/programs/pkey/key_app_writer.c
./external/mbedtls/programs/pkey/dh_server.c
./external/mbedtls/programs/pkey/pk_verify.c
./external/mbedtls/programs/pkey/dh_genprime.c
./external/mbedtls/programs/pkey/rsa_genkey.c
./external/mbedtls/programs/pkey/mpi_demo.c
./external/mbedtls/programs/pkey/dh_client.c
./external/mbedtls/programs/pkey/rsa_verify_pss.c
./external/mbedtls/programs/pkey/gen_key.c
./external/mbedtls/programs/pkey/rsa_verify.c
./external/mbedtls/programs/pkey/pk_sign.c
./external/mbedtls/programs/pkey/pk_decrypt.c
./external/mbedtls/programs/pkey/ecdh_curve25519.c
./external/mbedtls/programs/pkey/key_app.c
./external/mbedtls/programs/pkey/rsa_sign_pss.c
./external/mbedtls/programs/pkey/rsa_encrypt.c
./external/mbedtls/programs/pkey/rsa_sign.c
./external/nrf_cc310/common/integration_test_plat_utils.c
./external/nrf_tls/mbedtls/tls_interface.c
./external/nano-pb/pb_encode.c
./external/nano-pb/pb_common.c
./external/nano-pb/pb_decode.c
./external/nfc_adafruit_library/adafruit_pn532.c
./external/segger_rtt/SEGGER_RTT.c
./external/segger_rtt/SEGGER_RTT_printf.c
./external/segger_rtt/SEGGER_RTT_Syscalls_GCC.c
./external/segger_rtt/SEGGER_RTT_Syscalls_SES.c
./external/segger_rtt/SEGGER_RTT_Syscalls_IAR.c
./external/segger_rtt/SEGGER_RTT_Syscalls_KEIL.c
./external/nano/mock_pb_decode.c
./external/infineon/examples/ecdsa_utils/ecdsa_utils.c
./external/infineon/optiga/cmd/CommandLib.c
./external/infineon/optiga/common/Logger.c
./external/infineon/optiga/common/Util.c
./external/infineon/optiga/util/optiga_util.c
./external/infineon/optiga/comms/ifx_i2c/ifx_i2c_physical_layer.c
./external/infineon/optiga/comms/ifx_i2c/ifx_i2c.c
./external/infineon/optiga/comms/ifx_i2c/ifx_i2c_config.c
./external/infineon/optiga/comms/ifx_i2c/ifx_i2c_data_link_layer.c
./external/infineon/optiga/comms/ifx_i2c/ifx_i2c_transport_layer.c
./external/infineon/optiga/comms/optiga_comms.c
./external/infineon/optiga/dtls/DtlsRecordLayer.c
./external/infineon/optiga/dtls/MessageLayer.c
./external/infineon/optiga/dtls/HardwareCrypto.c
./external/infineon/optiga/dtls/DtlsHandshakeProtocol.c
./external/infineon/optiga/dtls/DtlsTransportLayer.c
./external/infineon/optiga/dtls/DtlsFlightHandler.c
./external/infineon/optiga/dtls/OCPConfig.c
./external/infineon/optiga/dtls/OCP.c
./external/infineon/optiga/dtls/DtlsWindowing.c
./external/infineon/optiga/dtls/AlertProtocol.c
./external/infineon/optiga/crypt/optiga_crypt.c
./external/infineon/pal/nrf5x/pal_ifx_i2c_config.c
./external/infineon/pal/nrf5x/pal_gpio.c
./external/infineon/pal/nrf5x/pal_os.c
./external/infineon/pal/nrf5x/pal_i2c.c
./external/infineon/pal/nrf5x/pal_os_lock.c
./external/freertos/source/stream_buffer.c
./external/freertos/source/event_groups.c
./external/freertos/source/timers.c
./external/freertos/source/croutine.c
./external/freertos/source/queue.c
./external/freertos/source/list.c
./external/freertos/source/portable/Common/mpu_wrappers.c
./external/freertos/source/portable/MemMang/heap_2.c
./external/freertos/source/portable/MemMang/heap_3.c
./external/freertos/source/portable/MemMang/heap_5.c
./external/freertos/source/portable/MemMang/heap_4.c
./external/freertos/source/portable/MemMang/heap_1.c
./external/freertos/source/tasks.c
./external/freertos/portable/GCC/nrf51/port.c
./external/freertos/portable/GCC/nrf52/port.c
./external/freertos/portable/IAR/nrf51/port.c
./external/freertos/portable/IAR/nrf52/port.c
./external/freertos/portable/ARM/nrf51/port.c
./external/freertos/portable/ARM/nrf52/port.c
./external/freertos/portable/CMSIS/nrf51/port_cmsis_systick.c
./external/freertos/portable/CMSIS/nrf51/port_cmsis.c
./external/freertos/portable/CMSIS/nrf52/port_cmsis_systick.c
./external/freertos/portable/CMSIS/nrf52/port_cmsis.c
./external/protothreads/pt-1.4/example-codelock.c
./external/protothreads/pt-1.4/example-small.c
./external/protothreads/pt-1.4/example-buffer.c
./external/lwip/doc/NO_SYS_SampleCode.c
./external/lwip/src/netif/ethernet.c
./external/lwip/src/netif/slipif.c
./external/lwip/src/netif/lowpan6.c
./external/lwip/src/netif/ethernetif.c
./external/lwip/src/netif/ppp/pppoe.c
./external/lwip/src/netif/ppp/demand.c
./external/lwip/src/netif/ppp/ipv6cp.c
./external/lwip/src/netif/ppp/pppapi.c
./external/lwip/src/netif/ppp/ecp.c
./external/lwip/src/netif/ppp/chap-md5.c
./external/lwip/src/netif/ppp/utils.c
./external/lwip/src/netif/ppp/multilink.c
./external/lwip/src/netif/ppp/ccp.c
./external/lwip/src/netif/ppp/vj.c
./external/lwip/src/netif/ppp/auth.c
./external/lwip/src/netif/ppp/ipcp.c
./external/lwip/src/netif/ppp/lcp.c
./external/lwip/src/netif/ppp/magic.c
./external/lwip/src/netif/ppp/pppol2tp.c
./external/lwip/src/netif/ppp/chap_ms.c
./external/lwip/src/netif/ppp/mppe.c
./external/lwip/src/netif/ppp/eap.c
./external/lwip/src/netif/ppp/eui64.c
./external/lwip/src/netif/ppp/upap.c
./external/lwip/src/netif/ppp/ppp.c
./external/lwip/src/netif/ppp/pppos.c
./external/lwip/src/netif/ppp/chap-new.c
./external/lwip/src/netif/ppp/polarssl/md5.c
./external/lwip/src/netif/ppp/polarssl/des.c
./external/lwip/src/netif/ppp/polarssl/md4.c
./external/lwip/src/netif/ppp/polarssl/sha1.c
./external/lwip/src/netif/ppp/polarssl/arc4.c
./external/lwip/src/netif/ppp/pppcrypt.c
./external/lwip/src/netif/ppp/fsm.c
./external/lwip/src/netif/etharp.c
./external/lwip/src/port/nrf_platform_port.c
./external/lwip/src/core/ip.c
./external/lwip/src/core/def.c
./external/lwip/src/core/mem.c
./external/lwip/src/core/init.c
./external/lwip/src/core/ipv6/ip6_frag.c
./external/lwip/src/core/ipv6/icmp6.c
./external/lwip/src/core/ipv6/nd6.c
./external/lwip/src/core/ipv6/dhcp6.c
./external/lwip/src/core/ipv6/ip6.c
./external/lwip/src/core/ipv6/ip6_addr.c
./external/lwip/src/core/ipv6/inet6.c
./external/lwip/src/core/ipv6/ethip6.c
./external/lwip/src/core/ipv6/mld6.c
./external/lwip/src/core/dhcp.c
./external/lwip/src/core/timeouts.c
./external/lwip/src/core/snmp/mib_structs.c
./external/lwip/src/core/snmp/msg_out.c
./external/lwip/src/core/snmp/msg_in.c
./external/lwip/src/core/snmp/asn1_enc.c
./external/lwip/src/core/snmp/mib2.c
./external/lwip/src/core/snmp/asn1_dec.c
./external/lwip/src/core/stats.c
./external/lwip/src/core/tcp.c
./external/lwip/src/core/netif.c
./external/lwip/src/core/raw.c
./external/lwip/src/core/dns.c
./external/lwip/src/core/inet_chksum.c
./external/lwip/src/core/tcp_in.c
./external/lwip/src/core/ipv4/dhcp.c
./external/lwip/src/core/ipv4/ip_frag.c
./external/lwip/src/core/ipv4/ip4_addr.c
./external/lwip/src/core/ipv4/ip4_frag.c
./external/lwip/src/core/ipv4/autoip.c
./external/lwip/src/core/ipv4/igmp.c
./external/lwip/src/core/ipv4/icmp.c
./external/lwip/src/core/ipv4/ip4.c
./external/lwip/src/core/ipv4/etharp.c
./external/lwip/src/core/memp.c
./external/lwip/src/core/tcp_out.c
./external/lwip/src/core/pbuf.c
./external/lwip/src/core/udp.c
./external/lwip/src/core/sys.c
./external/lwip/src/api/pppapi.c
./external/lwip/src/api/api_msg.c
./external/lwip/src/api/netbuf.c
./external/lwip/src/api/api_lib.c
./external/lwip/src/api/netdb.c
./external/lwip/src/api/err.c
./external/lwip/src/api/sockets.c
./external/lwip/src/api/tcpip.c
./external/lwip/src/api/netifapi.c
./external/lwip/src/apps/mqtt/mqtt.c
./external/lwip/src/apps/snmp/snmp_mib2.c
./external/lwip/src/apps/snmp/snmp_core.c
./external/lwip/src/apps/snmp/snmp_mib2_ip.c
./external/lwip/src/apps/snmp/snmp_mib2_system.c
./external/lwip/src/apps/snmp/snmpv3.c
./external/lwip/src/apps/snmp/snmpv3_dummy.c
./external/lwip/src/apps/snmp/snmp_threadsync.c
./external/lwip/src/apps/snmp/snmp_mib2_snmp.c
./external/lwip/src/apps/snmp/snmp_mib2_udp.c
./external/lwip/src/apps/snmp/snmp_msg.c
./external/lwip/src/apps/snmp/snmp_scalar.c
./external/lwip/src/apps/snmp/snmp_raw.c
./external/lwip/src/apps/snmp/snmp_traps.c
./external/lwip/src/apps/snmp/snmp_mib2_interfaces.c
./external/lwip/src/apps/snmp/snmpv3_mbedtls.c
./external/lwip/src/apps/snmp/snmp_table.c
./external/lwip/src/apps/snmp/snmp_mib2_icmp.c
./external/lwip/src/apps/snmp/snmp_mib2_tcp.c
./external/lwip/src/apps/snmp/snmp_netconn.c
./external/lwip/src/apps/snmp/snmp_asn1.c
./external/lwip/src/apps/snmp/snmp_pbuf_stream.c
./external/lwip/src/apps/mdns/mdns.c
./external/lwip/src/apps/netbiosns/netbiosns.c
./external/lwip/src/apps/sntp/sntp.c
./external/lwip/src/apps/lwiperf/lwiperf.c
./external/lwip/src/apps/tftp/tftp_server.c
./external/lwip/src/apps/httpd/fs.c
./external/lwip/src/apps/httpd/makefsdata/makefsdata.c
./external/lwip/src/apps/httpd/fsdata.c
./external/lwip/src/apps/httpd/httpd.c
./external/fprintf/nrf_fprintf_format.c
./external/fprintf/nrf_fprintf.c
./external/fnmatch/fnmatch.c
./external/cifra_AES128-EAX/blockwise.c
./external/cifra_AES128-EAX/cifra_cmac.c
./external/cifra_AES128-EAX/cifra_eax_aes.c
./external/cifra_AES128-EAX/gf128.c
./external/cifra_AES128-EAX/eax.c
./external/cifra_AES128-EAX/modes.c
./external/thedotfactory_fonts/orkney8pts.c
./external/thedotfactory_fonts/orkney24pts.c
./external/tile/tile_shim/tile_gatt_db/tile_gatt_db.c
./external/tile/tile_shim/tile_bdaddr/tile_bdaddr.c
./external/tile/tile_shim/tile_features/tile_features.c
./external/tile/tile_shim/tile_service/tile_service.c
./external/tile/tile_shim/tile_assert/tile_assert.c
./external/tile/tile_shim/tile_storage/tile_storage.c
./external/tile/tile_shim/tile_player/tile_player.c
./external/cJSON/cJSON.c
./external/cJSON/test.c
./modules/nrfx/mdk/system_nrf52810.c
./modules/nrfx/mdk/system_nrf52805.c
./modules/nrfx/mdk/system_nrf51.c
./modules/nrfx/mdk/system_nrf52.c
./modules/nrfx/mdk/system_nrf52811.c
./modules/nrfx/mdk/system_nrf52833.c
./modules/nrfx/mdk/system_nrf52840.c
./modules/nrfx/mdk/system_nrf9160.c
./modules/nrfx/mdk/system_nrf52820.c
./modules/nrfx/mdk/system_nrf5340_network.c
./modules/nrfx/mdk/system_nrf5340_application.c
./modules/nrfx/hal/nrf_ecb.c
./modules/nrfx/hal/nrf_nvmc.c
./modules/nrfx/drivers/src/nrfx_qspi.c
./modules/nrfx/drivers/src/nrfx_pwm.c
./modules/nrfx/drivers/src/nrfx_gpiote.c
./modules/nrfx/drivers/src/nrfx_systick.c
./modules/nrfx/drivers/src/nrfx_temp.c
./modules/nrfx/drivers/src/nrfx_comp.c
./modules/nrfx/drivers/src/nrfx_nvmc.c
./modules/nrfx/drivers/src/nrfx_spi.c
./modules/nrfx/drivers/src/nrfx_spim.c
./modules/nrfx/drivers/src/nrfx_power.c
./modules/nrfx/drivers/src/nrfx_dppi.c
./modules/nrfx/drivers/src/nrfx_timer.c
./modules/nrfx/drivers/src/nrfx_rng.c
./modules/nrfx/drivers/src/nrfx_twi.c
./modules/nrfx/drivers/src/nrfx_uarte.c
./modules/nrfx/drivers/src/nrfx_usbd.c
./modules/nrfx/drivers/src/nrfx_twi_twim.c
./modules/nrfx/drivers/src/nrfx_clock.c
./modules/nrfx/drivers/src/nrfx_ppi.c
./modules/nrfx/drivers/src/nrfx_twis.c
./modules/nrfx/drivers/src/nrfx_uart.c
./modules/nrfx/drivers/src/nrfx_rtc.c
./modules/nrfx/drivers/src/nrfx_qdec.c
./modules/nrfx/drivers/src/nrfx_saadc.c
./modules/nrfx/drivers/src/nrfx_i2s.c
./modules/nrfx/drivers/src/nrfx_twim.c
./modules/nrfx/drivers/src/nrfx_pdm.c
./modules/nrfx/drivers/src/nrfx_wdt.c
./modules/nrfx/drivers/src/nrfx_lpcomp.c
./modules/nrfx/drivers/src/nrfx_adc.c
./modules/nrfx/drivers/src/nrfx_nfct.c
./modules/nrfx/drivers/src/prs/nrfx_prs.c
./modules/nrfx/drivers/src/nrfx_swi.c
./modules/nrfx/drivers/src/nrfx_spis.c
./modules/nrfx/soc/nrfx_atomic.c
./components/drivers_ext/sx1509b/sx1509b.c
./components/drivers_ext/adns2080/adns2080.c
./components/drivers_ext/bh1745/bh1745.c
./components/drivers_ext/nrf6350/nrf6350.c
./components/drivers_ext/st7735/st7735.c
./components/drivers_ext/ili9341/ili9341.c
./components/drivers_ext/pcal6408a/pcal6408a.c
./components/drivers_ext/mpu6050/mpu6050.c
./components/drivers_ext/ds1624/ds1624.c
./components/drivers_ext/nrf21540/nrf21540.c
./components/drivers_ext/nrf21540/nrf21540_gpio.c
./components/drivers_ext/nrf21540/nrf21540_spi.c
./components/drivers_ext/cherry8x16/cherry8x16.c
./components/drivers_ext/mcp4725/mcp4725.c
./components/drivers_ext/max9850/max9850.c
./components/drivers_ext/ccs811/ccs811.c
./components/drivers_ext/synaptics_touchpad/synaptics_touchpad.c
./components/drivers_ext/hts221/hts221.c
./components/drivers_ext/lis2dh12/lis2dh12.c
./components/drivers_ext/uda1380/uda1380.c
./components/drivers_ext/lps22hb/lps22hb.c
./components/drivers_nrf/radio_config/radio_config.c
./components/drivers_nrf/sdio/sdio.c
./components/drivers_nrf/spi_master/spi_5W_master.c
./components/drivers_nrf/nrf_soc_nosd/nrf_soc.c
./components/drivers_nrf/nrf_soc_nosd/nrf_nvic.c
./components/drivers_nrf/twi_master/deprecated/twi_hw_master.c
./components/drivers_nrf/twi_master/deprecated/twi_sw_master.c
./components/boards/boards.c
./components/libraries/hardfault/nrf51/handler/hardfault_handler_keil.c
./components/libraries/hardfault/nrf51/handler/hardfault_handler_gcc.c
./components/libraries/hardfault/nrf51/handler/hardfault_handler_iar.c
./components/libraries/hardfault/nrf52/handler/hardfault_handler_keil.c
./components/libraries/hardfault/nrf52/handler/hardfault_handler_gcc.c
./components/libraries/hardfault/nrf52/handler/hardfault_handler_iar.c
./components/libraries/hardfault/hardfault_implementation.c
./components/libraries/mpu/nrf_mpu_lib.c
./components/libraries/csense_drv/nrf_drv_csense.c
./components/libraries/mem_manager/mem_manager.c
./components/libraries/led_softblink/led_softblink.c
./components/libraries/experimental_task_manager/task_manager.c
./components/libraries/sensorsim/sensorsim.c
./components/libraries/sdcard/app_sdcard.c
./components/libraries/timer/app_timer_rtx.c
./components/libraries/timer/app_timer2.c
./components/libraries/timer/app_timer_freertos.c
./components/libraries/timer/app_timer.c
./components/libraries/timer/drv_rtc.c
./components/libraries/fds/fds.c
./components/libraries/util/app_error_handler_keil.c
./components/libraries/util/app_error_handler_iar.c
./components/libraries/util/app_error_weak.c
./components/libraries/util/app_error.c
./components/libraries/util/app_util_platform.c
./components/libraries/util/nrf_assert.c
./components/libraries/util/sdk_mapped_flags.c
./components/libraries/util/app_error_handler_gcc.c
./components/libraries/strerror/nrf_strerror.c
./components/libraries/sha256/sha256.c
./components/libraries/crc32/crc32.c
./components/libraries/hci/hci_transport.c
./components/libraries/hci/hci_mem_pool.c
./components/libraries/hci/hci_slip.c
./components/libraries/atomic/nrf_atomic.c
./components/libraries/block_dev/empty/nrf_block_dev_empty.c
./components/libraries/block_dev/qspi/nrf_serial_flash_params.c
./components/libraries/block_dev/qspi/nrf_block_dev_qspi.c
./components/libraries/block_dev/ram/nrf_block_dev_ram.c
./components/libraries/block_dev/sdc/nrf_block_dev_sdc.c
./components/libraries/spi_mngr/nrf_spi_mngr.c
./components/libraries/svc/nrf_svc_handler.c
./components/libraries/usbd/app_usbd_core.c
./components/libraries/usbd/app_usbd_string_desc.c
./components/libraries/usbd/app_usbd.c
./components/libraries/usbd/app_usbd_serial_num.c
./components/libraries/usbd/class/hid/generic/app_usbd_hid_generic.c
./components/libraries/usbd/class/hid/kbd/app_usbd_hid_kbd.c
./components/libraries/usbd/class/hid/app_usbd_hid.c
./components/libraries/usbd/class/hid/mouse/app_usbd_hid_mouse.c
./components/libraries/usbd/class/audio/app_usbd_audio.c
./components/libraries/usbd/class/msc/app_usbd_msc.c
./components/libraries/usbd/class/cdc/acm/app_usbd_cdc_acm.c
./components/libraries/usbd/class/dummy/app_usbd_dummy.c
./components/libraries/usbd/class/nrf_dfu_trigger/app_usbd_nrf_dfu_trigger.c
./components/libraries/button/app_button.c
./components/libraries/gpiote/app_gpiote.c
./components/libraries/pwr_mgmt/nrf_pwr_mgmt.c
./components/libraries/queue/nrf_queue.c
./components/libraries/simple_timer/app_simple_timer.c
./components/libraries/scheduler/app_scheduler.c
./components/libraries/scheduler/app_scheduler_serconn.c
./components/libraries/csense/nrf_csense.c
./components/libraries/cli/cli_utils_cmds.c
./components/libraries/cli/ble_uart/nrf_cli_ble_uart.c
./components/libraries/cli/nrf_cli.c
./components/libraries/cli/cdc_acm/nrf_cli_cdc_acm.c
./components/libraries/cli/libuarte/nrf_cli_libuarte.c
./components/libraries/cli/rtt/nrf_cli_rtt.c
./components/libraries/cli/uart/nrf_cli_uart.c
./components/libraries/bsp/bsp_btn_ant.c
./components/libraries/bsp/bsp_nfc.c
./components/libraries/bsp/bsp.c
./components/libraries/bsp/bsp_btn_ble.c
./components/libraries/bsp/bsp_cli.c
./components/libraries/crc16/crc16.c
./components/libraries/memobj/nrf_memobj.c
./components/libraries/twi_sensor/nrf_twi_sensor.c
./components/libraries/libuarte/nrf_libuarte_async.c
./components/libraries/libuarte/nrf_libuarte_drv.c
./components/libraries/slip/slip.c
./components/libraries/atomic_flags/nrf_atflags.c
./components/libraries/low_power_pwm/low_power_pwm.c
./components/libraries/bootloader/nrf_bootloader_dfu_timers.c
./components/libraries/bootloader/nrf_bootloader_app_start_final.c
./components/libraries/bootloader/nrf_bootloader_wdt.c
./components/libraries/bootloader/serial_dfu/nrf_dfu_serial.c
./components/libraries/bootloader/serial_dfu/nrf_dfu_serial_usb.c
./components/libraries/bootloader/serial_dfu/nrf_dfu_serial_uart.c
./components/libraries/bootloader/ble_dfu/nrf_dfu_ble.c
./components/libraries/bootloader/nrf_bootloader_fw_activation.c
./components/libraries/bootloader/nrf_bootloader_app_start.c
./components/libraries/bootloader/nrf_bootloader.c
./components/libraries/bootloader/nrf_bootloader_info.c
./components/libraries/bootloader/ant_dfu/nrf_dfu_ant.c
./components/libraries/bootloader/dfu/nrf_dfu_svci_handler.c
./components/libraries/bootloader/dfu/nrf_dfu_trigger_usb.c
./components/libraries/bootloader/dfu/nrf_dfu_utils.c
./components/libraries/bootloader/dfu/nrf_dfu_validation.c
./components/libraries/bootloader/dfu/nrf_dfu_req_handler.c
./components/libraries/bootloader/dfu/nrf_dfu_mbr.c
./components/libraries/bootloader/dfu/nrf_dfu.c
./components/libraries/bootloader/dfu/nrf_dfu_settings.c
./components/libraries/bootloader/dfu/nrf_dfu_svci.c
./components/libraries/bootloader/dfu/nrf_dfu_settings_svci.c
./components/libraries/bootloader/dfu/nrf_dfu_transport.c
./components/libraries/bootloader/dfu/dfu-cc.pb.c
./components/libraries/bootloader/dfu/nrf_dfu_handling_error.c
./components/libraries/bootloader/dfu/nrf_dfu_ver_validation.c
./components/libraries/bootloader/dfu/nrf_dfu_flash.c
./components/libraries/fstorage/nrf_fstorage_sd.c
./components/libraries/fstorage/nrf_fstorage.c
./components/libraries/fstorage/nrf_fstorage_nvmc.c
./components/libraries/experimental_section_vars/nrf_section_iter.c
./components/libraries/gfx/nrf_gfx.c
./components/libraries/ringbuf/nrf_ringbuf.c
./components/libraries/atomic_fifo/nrf_atfifo.c
./components/libraries/fifo/app_fifo.c
./components/libraries/ecc/ecc.c
./components/libraries/sortlist/nrf_sortlist.c
./components/libraries/crypto/nrf_crypto_rng.c
./components/libraries/crypto/nrf_crypto_ecdh.c
./components/libraries/crypto/nrf_crypto_eddsa.c
./components/libraries/crypto/nrf_crypto_hmac.c
./components/libraries/crypto/nrf_crypto_hkdf.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_ecdh.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_aes.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_hmac.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_init.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_ecdsa.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_ecc.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_hash.c
./components/libraries/crypto/backend/mbedtls/mbedtls_backend_aes_aead.c
./components/libraries/crypto/backend/oberon/oberon_backend_hash.c
./components/libraries/crypto/backend/oberon/oberon_backend_hmac.c
./components/libraries/crypto/backend/oberon/oberon_backend_ecc.c
./components/libraries/crypto/backend/oberon/oberon_backend_ecdsa.c
./components/libraries/crypto/backend/oberon/oberon_backend_chacha_poly_aead.c
./components/libraries/crypto/backend/oberon/oberon_backend_ecdh.c
./components/libraries/crypto/backend/oberon/oberon_backend_eddsa.c
./components/libraries/crypto/backend/cifra/cifra_backend_aes_aead.c
./components/libraries/crypto/backend/cc310/cc310_backend_init.c
./components/libraries/crypto/backend/cc310/cc310_backend_mutex.c
./components/libraries/crypto/backend/cc310/cc310_backend_ecdh.c
./components/libraries/crypto/backend/cc310/cc310_backend_aes.c
./components/libraries/crypto/backend/cc310/cc310_backend_aes_aead.c
./components/libraries/crypto/backend/cc310/cc310_backend_shared.c
./components/libraries/crypto/backend/cc310/cc310_backend_hmac.c
./components/libraries/crypto/backend/cc310/cc310_backend_ecc.c
./components/libraries/crypto/backend/cc310/cc310_backend_ecdsa.c
./components/libraries/crypto/backend/cc310/cc310_backend_eddsa.c
./components/libraries/crypto/backend/cc310/cc310_backend_rng.c
./components/libraries/crypto/backend/cc310/cc310_backend_chacha_poly_aead.c
./components/libraries/crypto/backend/cc310/cc310_backend_hash.c
./components/libraries/crypto/backend/nrf_sw/nrf_sw_backend_hash.c
./components/libraries/crypto/backend/nrf_hw/nrf_hw_backend_rng.c
./components/libraries/crypto/backend/nrf_hw/nrf_hw_backend_rng_mbedtls.c
./components/libraries/crypto/backend/nrf_hw/nrf_hw_backend_init.c
./components/libraries/crypto/backend/optiga/optiga_backend_ecdh.c
./components/libraries/crypto/backend/optiga/optiga_backend_rng.c
./components/libraries/crypto/backend/optiga/optiga_backend_ecdsa.c
./components/libraries/crypto/backend/optiga/optiga_backend_init.c
./components/libraries/crypto/backend/optiga/optiga_backend_utils.c
./components/libraries/crypto/backend/optiga/optiga_backend_ecc.c
./components/libraries/crypto/backend/cc310_bl/cc310_bl_backend_ecdsa.c
./components/libraries/crypto/backend/cc310_bl/cc310_bl_backend_init.c
./components/libraries/crypto/backend/cc310_bl/cc310_bl_backend_shared.c
./components/libraries/crypto/backend/cc310_bl/cc310_bl_backend_hash.c
./components/libraries/crypto/backend/cc310_bl/cc310_bl_backend_ecc.c
./components/libraries/crypto/backend/micro_ecc/micro_ecc_backend_ecdh.c
./components/libraries/crypto/backend/micro_ecc/micro_ecc_backend_ecdsa.c
./components/libraries/crypto/backend/micro_ecc/micro_ecc_backend_ecc.c
./components/libraries/crypto/nrf_crypto_ecdsa.c
./components/libraries/crypto/nrf_crypto_error.c
./components/libraries/crypto/nrf_crypto_aes_shared.c
./components/libraries/crypto/nrf_crypto_aead.c
./components/libraries/crypto/nrf_crypto_init.c
./components/libraries/crypto/nrf_crypto_ecc.c
./components/libraries/crypto/nrf_crypto_hash.c
./components/libraries/crypto/nrf_crypto_shared.c
./components/libraries/crypto/nrf_crypto_aes.c
./components/libraries/balloc/nrf_balloc.c
./components/libraries/pwm/app_pwm.c
./components/libraries/log/src/nrf_log_frontend.c
./components/libraries/log/src/nrf_log_default_backends.c
./components/libraries/log/src/nrf_log_backend_serial.c
./components/libraries/log/src/nrf_log_backend_uart.c
./components/libraries/log/src/nrf_log_backend_flash.c
./components/libraries/log/src/nrf_log_str_formatter.c
./components/libraries/log/src/nrf_log_backend_rtt.c
./components/libraries/stack_guard/nrf_stack_guard.c
./components/libraries/twi_mngr/nrf_twi_mngr.c
./components/libraries/uart/app_uart.c
./components/libraries/uart/app_uart_fifo.c
./components/libraries/uart/retarget.c
./components/proprietary_rf/esb/nrf_esb.c
./components/proprietary_rf/gzll/nrf_gzp_device.c
./components/proprietary_rf/gzll/nrf_gzp.c
./components/proprietary_rf/gzll/nrf_gzp_host.c
./components/proprietary_rf/gzll/nrf_gzp_host_nrf5x.c
)

